spec: grammar_draft3.tex
	pdflatex grammar_draft3.tex
	makeindex grammar_draft3.idx
	pdflatex grammar_draft3.tex
	evince grammar_draft3.pdf

quick: quick_start.tex
	pdflatex quick_start.tex
	evince quick_start.pdf
